
name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Check for differences after build
        run: git diff --ignore-space-at-eol --exit-code
